title: Yi Zhao
description: [Github](https://github.com/zhaoyi11)  |  [Publications]()  |  [Blog](./blog/blog.md)  |  [Experience]()  |   [Contact]() Ph.D candidate at Aalto Robot Learning Group.
theme: jekyll-theme-tactile
